#!/usr/bin/env bash

mkdir -p pkg/src
PKG_LIST=$(ls pkg/src | tr " " "\n")

case "${1:2}" in
	"version")
		echo "bildo 0.01.1"
		;;
	"help")
		echo "./bildo [arg]"
		echo ""
		echo "arguments:"
		echo "--help:    show this screen"
		echo "--list:    list all directories in pkg/src"
		echo "--update:  update bildo repo, git pull all pkg/src directories"
		echo "--upgrade: compile all pkg/src directories using bildo repo build scripts"
		echo "--version: display current version of bildo"
		echo ""
		;;
	"list")
		echo "$PKG_LIST"
		;;
	"update")
		echo -n "updating bildo repo..."
		git pull > /dev/null 2>&1
		echo " done"
		echo -n "updating projects  ..."
		for l in $PKG_LIST; do
			cd pkg/src/"$l"
			git pull > /dev/null 2>&1
			cd ../../..
		done
		echo " done"
		;;
	"upgrade")
		for l in $PKG_LIST; do
			if [ ! -f pkg/repo/"$l".sh ]; then
                                echo "no build script for $l available"
                                continue
                        fi
			bash pkg/repo/"${l}".sh
		done
		;;
	*)
		echo "unrecognized command"
		;;
esac
