#!/usr/bin/env bash

mkdir -p pkg/src
PKG_LIST=$(ls pkg/src | tr " " "\n")

OPTION="$1"
if [ -z "$OPTION" ]; then
	OPTION="--help"
fi

case "${OPTION:2}" in
	"version")
		echo "bildo 0.01.1"
		;;
	"help")
		echo "./bildo [arg]"
		echo ""
		echo "arguments:"
		echo "--help:    show this screen"
		echo "--list:    list all directories in pkg/src"
		echo "--update:  update bildo repo, git pull all pkg/src directories"
		echo "--rebuild: compile a package. defaults to all if no package name is given"
		echo "--version: display current version of bildo"
		echo ""
		;;
	"list")
		echo "$PKG_LIST"
		;;
	"update")
		echo -n "updating bildo repo..."
		git pull > /dev/null 2>&1
		echo " done"
		echo
		for l in $PKG_LIST; do
			echo "checking: $l"
			cd pkg/src/"$l"
			git pull
			echo
			cd ../../..
		done
		;;
	"rebuild")
		if [ ! -z "$2" ]; then
			if [ ! -z "$3" ]; then
				echo "ERROR: only one package updatable at a time"
				exit
			fi
			if [ ! -f pkg/repo/"$2".sh ]; then
				echo "ERROR: no build script for $2 available"
				exit
			else
				bash pkg/repo/"$2".sh build
			fi
			exit
		fi
		for l in $PKG_LIST; do
			if [ ! -f pkg/repo/"$l".sh ]; then
                                echo "ERROR: no build script for $l available"
                                continue
                        fi
			bash pkg/repo/"${l}".sh build
		done
		;;
	*)
		echo "ERROR: unrecognized command"
		;;
esac
