#!/usr/bin/env bash

mkdir -p pkg/src
PKG_LIST=$(ls pkg/src | tr " " "\n")

OPTION="$1"
if [ -z "$OPTION" ]; then
	OPTION="--help"
fi

case "$OPTION" in
	"--version" | "-v")
		echo "despot 0.01.3"
		;;
	"--help" | "-h")
		echo "./despot [arg]"
		echo ""
		echo "arguments:"
		echo "--help          | show this screen"
		echo "--install [PKG] | compile a package"
		echo "--list          | list all directories in pkg/src"
		echo "--remove [PKG]  | remove given package"       
		echo "--update        | git pull pkg/src & pkg/repo"
		echo "--version       | display current version of despot"
		echo ""
		;;
	"--list" | "-l")
		echo "$PKG_LIST"
		;;
	"--remove" | "-r")
		if [ ! -z "$2" ]; then
			if [ ! -z "$3" ]; then
				echo "ERROR: only one package updatable at a time"
				exit
			fi
			if [ ! -f pkg/repo/"$2".bash ]; then
				echo "ERROR: draumaz has yet to write a build script for $2"
				exit
			else
				bash pkg/repo/"$2".bash uninstall
				echo "uninstalled."
			fi
			exit
		else
			echo "ERROR: no package name provided for removal."
			exit
		fi
		;;
	"--update" | "-u")
		echo -n "updating despot repo..."
		git pull > /dev/null 2>&1
		echo " done"
		echo
		for l in $PKG_LIST; do
			echo "checking: $l"
			cd pkg/src/"$l"
			git pull
			echo
			cd ../../..
		done
		;;
	"--install" | "-i")
		if [ ! -z "$2" ]; then
			if [ "$2" == "-a" ] || [ "$2" == "--all" ]; then
				echo -e "updating all packages\n"
				for l in $PKG_LIST; do
					if [ ! -f pkg/repo/"$l".bash ]; then
						echo "ERROR: no build script for $l available"
						continue
					fi
					bash pkg/repo/"${l}".bash build
				done
			fi
		fi
		if [ -z "$2" ]; then
			echo "ERROR: no package name provided for install"
			exit
		fi
		if [ ! -f pkg/repo/"$2".bash ]; then
			echo "ERROR: draumaz has yet to write a build script for $2"
			exit
		else if [ ! -e pkg/repo/"$2" ]; then
			bash pkg/repo/"$2".bash sources
		fi fi
		bash pkg/repo/"$2".bash build
		echo "installed."
		exit
		;;
	*)
		echo "ERROR: unrecognized command"
		;;
esac
